# Generated by Django 2.2.7 on 2020-02-12 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Text to appear on the tab under the icon', max_length=30)),
                ('icon', models.CharField(help_text='Font awesome icon v4. Just the end part, e.g. fa-clock-o -> clock-o', max_length=20)),
                ('position', models.PositiveIntegerField()),
                ('visible', models.BooleanField(help_text='If the tab should be displayed')),
            ],
        ),
        migrations.CreateModel(
            name='TabGroup',
            fields=[
                ('button_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tabsManager.Button')),
            ],
            bases=('tabsManager.button',),
        ),
        migrations.CreateModel(
            name='Tab',
            fields=[
                ('button_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tabsManager.Button')),
                ('url', models.URLField(null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tabsManager.TabGroup')),
            ],
            bases=('tabsManager.button',),
        ),
    ]
