# Generated by Django 2.2.7 on 2020-05-13 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabsManager', '0004_auto_20200924_1729'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logo',
        ),
    ]
