# Generated by Django 2.2.13 on 2020-08-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achillesresults',
            name='stratum_1',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='achillesresults',
            name='stratum_2',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='achillesresults',
            name='stratum_3',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='achillesresults',
            name='stratum_4',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='achillesresults',
            name='stratum_5',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='achillesresultsarchive',
            name='stratum_1',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='achillesresultsarchive',
            name='stratum_2',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='achillesresultsarchive',
            name='stratum_3',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='achillesresultsarchive',
            name='stratum_4',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='achillesresultsarchive',
            name='stratum_5',
            field=models.TextField(null=True),
        ),
    ]
