# Generated by Django 2.2.7 on 2020-05-11 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasource',
            old_name='slug',
            new_name='acronym',
        ),
    ]
