# Generated by Django 2.2.13 on 2020-09-23 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_auto_20200803_1352'),
        ('uploader', '0002_auto_20200519_1948'),
    ]

    operations = [
    ]
