# Generated by Django 2.2.16 on 2020-09-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uploader", "0003_merge_20200923_1703"),
    ]

    operations = [
        migrations.CreateModel(
            name="Concept",
            fields=[
                (
                    "concept_id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("concept_name", models.CharField(max_length=255)),
                ("domain_id", models.CharField(max_length=20)),
                ("vocabulary_id", models.CharField(max_length=20)),
                ("concept_class_id", models.CharField(max_length=20)),
                ("standard_concept", models.CharField(max_length=1, null=True)),
                ("concept_code", models.CharField(max_length=50)),
                ("valid_start_date", models.DateField()),
                ("valid_end_date", models.DateField()),
                ("invalid_reason", models.CharField(max_length=1, null=True)),
            ],
            options={
                "db_table": "concept",
            },
        ),
    ]
