# Generated by Django 2.2.16 on 2020-11-09 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uploader", "0005_auto_20201002_1125"),
    ]

    operations = [
        migrations.AddField(
            model_name="achillesresults",
            name="avg_value",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="achillesresults",
            name="max_value",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="achillesresults",
            name="median_value",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="achillesresults",
            name="min_value",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="achillesresults",
            name="p10_value",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="achillesresults",
            name="p25_value",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="achillesresults",
            name="p75_value",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="achillesresults",
            name="p90_value",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="achillesresults",
            name="stdev_value",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="achillesresultsarchive",
            name="avg_value",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="achillesresultsarchive",
            name="max_value",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="achillesresultsarchive",
            name="median_value",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="achillesresultsarchive",
            name="min_value",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="achillesresultsarchive",
            name="p10_value",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="achillesresultsarchive",
            name="p25_value",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="achillesresultsarchive",
            name="p75_value",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="achillesresultsarchive",
            name="p90_value",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="achillesresultsarchive",
            name="stdev_value",
            field=models.FloatField(null=True),
        ),
    ]
