# Generated by Django 2.2.16 on 2020-12-12 11:58

from django.db import migrations, models
import uploader.models


class Migration(migrations.Migration):

    dependencies = [
        ("uploader", "0006_auto_20201109_2152"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadhistory",
            name="zip_file",
            field=models.FileField(default=None, upload_to=uploader.models.zip_file_path),
            preserve_default=False,
        ),
    ]
