# Generated by Django 2.2.16 on 2020-12-12 11:58

import uploader.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uploader", "0007_auto_20201212_2012"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadhistory",
            name="upload_file",
            field=models.FileField(
                default=None, upload_to=uploader.models.upload_file_path
            ),
            preserve_default=False,
        ),
    ]
