# Generated by Django 2.2.16 on 2020-12-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uploader", "0007_auto_20201212_2012"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasource",
            name="release_date",
            field=models.CharField(
                help_text="Date at which DB is available for research for current release.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="uploadhistory",
            name="cdm_release_date",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="uploadhistory",
            name="cdm_version",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="uploadhistory",
            name="generation_date",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="uploadhistory",
            name="r_package_version",
            field=models.CharField(max_length=50),
        ),
    ]
