# Generated by Django 2.2.17 on 2020-12-21 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("uploader", "0008_auto_20201217_1425"),
        ("uploader", "0008_uploadhistory_upload_file"),
    ]

    operations = []
