# Generated by Django 2.2.17 on 2021-05-06 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0009_auto_20210112_1719'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadhistory',
            options={'get_latest_by': 'upload_date', 'ordering': ('-upload_date',)},
        ),
        migrations.AddField(
            model_name='datasource',
            name='draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='achillesresults',
            name='data_source',
            field=models.ForeignKey(limit_choices_to={'draft': False}, on_delete=django.db.models.deletion.CASCADE, to='uploader.DataSource'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='release_date',
            field=models.CharField(blank=True, help_text='Date at which DB is available for research for current release.', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='AchillesResultsDraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_id', models.BigIntegerField()),
                ('stratum_1', models.TextField(null=True)),
                ('stratum_2', models.TextField(null=True)),
                ('stratum_3', models.TextField(null=True)),
                ('stratum_4', models.TextField(null=True)),
                ('stratum_5', models.TextField(null=True)),
                ('count_value', models.BigIntegerField()),
                ('min_value', models.BigIntegerField(null=True)),
                ('max_value', models.BigIntegerField(null=True)),
                ('avg_value', models.FloatField(null=True)),
                ('stdev_value', models.FloatField(null=True)),
                ('median_value', models.BigIntegerField(null=True)),
                ('p10_value', models.BigIntegerField(null=True)),
                ('p25_value', models.BigIntegerField(null=True)),
                ('p75_value', models.BigIntegerField(null=True)),
                ('p90_value', models.BigIntegerField(null=True)),
                ('data_source', models.ForeignKey(limit_choices_to={'draft': True}, on_delete=django.db.models.deletion.CASCADE, to='uploader.DataSource')),
            ],
            options={
                'db_table': 'achilles_results_draft',
            },
        ),
        migrations.AddIndex(
            model_name='achillesresultsdraft',
            index=models.Index(fields=['data_source'], name='achilles_re_data_so_009db8_idx'),
        ),
    ]
