# Generated by Django 2.2.17 on 2021-01-23 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("uploader", "0009_auto_20210112_1719"),
        ("uploader", "0008_uploadhistory_upload_file"),
    ]

    operations = []
