# Generated by Django 2.2.17 on 2021-01-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uploader", "0009_merge_20201221_1442"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadhistory",
            name="cdm_version",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="uploadhistory",
            name="generation_date",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="uploadhistory",
            name="r_package_version",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="uploadhistory",
            name="vocabulary_version",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
