# Generated by Django 2.2.17 on 2021-06-02 10:36

import uploader.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uploader", "0011_country_alpha2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasource",
            name="hash",
            field=models.CharField(
                blank=True,
                default=uploader.models.default_hash_generator,
                max_length=255,
                unique=True,
            ),
        ),
        migrations.RunSQL(
            "INSERT INTO achilles_results ("
            "    analysis_id,"
            "    stratum_1, stratum_2, stratum_3, stratum_4, stratum_5,"
            "    count_value,"
            "    min_value, max_value,"
            "    avg_value, stdev_value,"
            "    median_value,"
            "    p10_value, p25_value, p75_value, p90_value,"
            "    data_source_id"
            ") select "
            "    analysis_id,"
            "    stratum_1, stratum_2, stratum_3, stratum_4, stratum_5,"
            "    count_value,"
            "    min_value, max_value,"
            "    avg_value, stdev_value,"
            "    median_value,"
            "    p10_value, p25_value, p75_value, p90_value,"
            "    data_source_id "
            "from achilles_results_draft;"
        ),
        migrations.DeleteModel(
            name="AchillesResultsDraft",
        ),
    ]
