# Generated by Django 2.2.17 on 2021-06-02 10:36

from django.db import migrations, models
import uploader.models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0011_country_alpha2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='hash',
            field=models.CharField(
                blank=True,
                default=uploader.models.default_hash_generator,
                max_length=255,
                unique=True,
            ),
        ),
        migrations.RunSQL("INSERT INTO achilles_results SELECT * FROM achilles_results_draft"),
        migrations.DeleteModel(
            name='AchillesResultsDraft',
        ),
    ]
