# Generated by Django 2.2.17 on 2021-06-09 16:37

from django.db import migrations, models
import uploader.models


class Migration(migrations.Migration):

    dependencies = [
        ("uploader", "0011_country_alpha2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="achillesresults",
            name="max_value",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="achillesresults",
            name="median_value",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="achillesresults",
            name="min_value",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="achillesresults",
            name="p10_value",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="achillesresults",
            name="p25_value",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="achillesresults",
            name="p75_value",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="achillesresults",
            name="p90_value",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="achillesresultsdraft",
            name="max_value",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="achillesresultsdraft",
            name="median_value",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="achillesresultsdraft",
            name="min_value",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="achillesresultsdraft",
            name="p10_value",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="achillesresultsdraft",
            name="p25_value",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="achillesresultsdraft",
            name="p75_value",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="achillesresultsdraft",
            name="p90_value",
            field=models.FloatField(null=True),
        ),
    ]
