# Generated by Django 2.2.16 on 2020-09-29 16:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materialized_queries_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materializedquery",
            name="name",
            field=models.CharField(
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[_0-9a-zA-Z]+$",
                        'Only alphanumeric characters and the character "_" are allowed.',
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="materializedquery",
            name="dashboards",
            field=models.CharField(
                blank=True,
                help_text="In which dashboards is the view being used. This is field is Optional field and has the "
                "intent to help on organization and search among the different queries.",
                max_length=100,
                null=True,
            ),
        ),
    ]
