# Generated by Django 2.2.16 on 2020-12-17 13:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materialized_queries_manager", "0002_auto_20200929_1636"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materializedquery",
            name="name",
            field=models.CharField(
                max_length=100,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[_0-9a-zA-Z]+$",
                        'Only alphanumeric characters and the character "_" are allowed.',
                    )
                ],
            ),
        ),
    ]
